### ISSUE TITLE
Wallet modal missing recent transactions and copy address button

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-swap-interface#114]
![image](https://user-images.githubusercontent.com/71833681/103647181-38204c80-4f9e-11eb-97ed-7de214cda7a8.png)

**Bug Description**
When we moved to the UI Kit, we lost the "Recent transactions" and also "Copy address" button

**Comment by hachiojidev** [comment]
The copy address button will be addressed here - https://github.com/pancakeswap/pancake-uikit/issues/113
