### ISSUE TITLE
Missing Binance Smart Chain Wallet Connection - Users funds are stuck

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-swap-interface#116]
![image](https://user-images.githubusercontent.com/71833681/103720098-f0390e00-500d-11eb-8fba-f229d547d12f.png)

**Bug Description**
When migrating to UI Kit wallet connection, we removed Binance Smart chain Wallet connection options

**Steps to Reproduce**
1. Go to exchange - click unlock wallet
...

**Expected Behavior**
We should have additional options for Binance Smart Chain wallet.

**Comment by hachiojidev** [comment]
@Chef-Chungus Can we remove SafePal from this card and create a new one?

**Comment by Chef-Chungus** [comment]
@hachiojidev done
