### ISSUE TITLE
Logo on menu directs you to wrong page

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-swap-interface#119]
![image](https://user-images.githubusercontent.com/71833681/103722580-a5ba9000-5013-11eb-91bb-11454a8f466b.png)

**Bug Description**
Clicking on the menu logo on the exchange leads you to the exchange homepage

**Steps to Reproduce**
1. Go to exchange.pancakeswap.finance
2. Click on the logo
...

**Expected Behavior**
It should link you to https://pancakeswap.finance

**Comment by hachiojidev** [comment]
Will be fixed with the new menu and https://github.com/pancakeswap/pancake-uikit/pull/114
