### ISSUE TITLE
WalletConnect link not working, js site crashes

### ISSUE THREAD

**Issue by testacode** [pancakeswap/pancake-swap-interface#124]
**Bug Description**
When navigating to exchange.pancakeswap.finance with latest version of Chrome or Safari (from OSX Big Sur also latest version) and trying to connect with Walletconnect after reading the QR with my iPhone 12 (iOS latest version) and also latest version of TrustWallet the site crashes. Below it's the screenshot.
![image](https://user-images.githubusercontent.com/1852080/103843151-11cde000-5076-11eb-82cd-e80b213f78c8.png)

**Steps to Reproduce**
1. Go to exchange.pancakeswap.finance.
2. Click on "connect" button (upper right).
3. Select "WalletConnect".
4. Scan QR with TrustWallet
5. Site JS crashes.
...

**Expected Behavior**
The expected behavior should be that the app won't crash and let me stake or trade my tokens.

**Video**
![uxjDVzMMAI](https://user-images.githubusercontent.com/1852080/103844035-c74d6300-5077-11eb-91db-2fa304b34270.gif)

**Comment by testacode** [comment]
It's working now. It just wasn't a couple of hours ago!! You can close this!

**Comment by testacode** [comment]
It's happening on the exchange now

**Comment by xandercakes** [comment]
https://user-images.githubusercontent.com/77136438/103978143-0c38ce80-5138-11eb-8268-88bebfd490a0.mp4

**Comment by xandercakes** [comment]
The same issue occurs when trying us WalletConnect and SafePal on exchange.pancakeswap.finance. Reproduced the above issue with WalletConnect using both SafePal and Trust Wallet (Android Version 11, Brave and Firefox).

**Comment by NinZine** [comment]
Reproduced both on Android and iOS with Trust Wallet.

```
TypeError: Cannot read property 'address' of undefined
    at main.bd05afab.chunk.js:1
    at Sb (main.bd05afab.chunk.js:1)
    at Rb (main.bd05afab.chunk.js:1)
    at no (4.b8eba4b2.chunk.js:1)
    at Jo (4.b8eba4b2.chunk.js:1)
    at Xs (4.b8eba4b2.chunk.js:1)
    at Tu (4.b8eba4b2.chunk.js:1)
    at Cu (4.b8eba4b2.chunk.js:1)
    at xu (4.b8eba4b2.chunk.js:1)
    at vu (4.b8eba4b2.chunk.js:1)
```

**Comment by trumhemcut** [comment]
me too.

**Comment by taasaa** [comment]
Happens to me too. Any idea when it will be addressed? I can't use pancake with my wallets

**Comment by testacode** [comment]
> Happens to me too. Any idea when it will be addressed? I can't use pancake with my wallets

Actually you can. You can use any network compatible wallet with a web3 browser. For example with [SafePal's App](https://www.safepal.io/download).

**Comment by adaamz** [comment]
same here, when I proposed myself to fix this bug i was banned on Telegram...

**Comment by RabbitDoge** [comment]
> same here, when I proposed myself to fix this bug i was banned on Telegram...

If you want to help solving this issue, please propose a solution here.

**Comment by adaamz** [comment]
Looks like MetaMask doesnt work too. Should I create new issue?

**Comment by rapinto** [comment]
same problem using "wallet connect" from Trust Wallet iOS mobile App.

**Comment by perimbit** [comment]
Same issue trying to use the exchange. I tried to connect using the "wallet connect" from Trust Wallet iOS mobile. I tried it from my PC and my cellphone. Both the same problem

**Comment by testacode** [comment]
This still happening says a lot about the development path of the team. Too bad.

**Comment by RabbitDoge** [comment]
Solved
