### ISSUE TITLE
[Listing] Request listing for WOOP ( Woonkly Power)

### ISSUE THREAD

**Issue by facumartinarguello** [pancakeswap/pancake-swap-interface#144]
**Token information**

{
"name": "Woonkly Power",
"symbol": "WOOP",
"address": "0x8b303d5bbfbbf46f1a4d9741e491e06986894e18",
"chainId": 56,
"decimals": 18,
"logoURI": "/images/coins/WOOP.png"
}

![woop](https://user-images.githubusercontent.com/61710998/104762138-23914080-5764-11eb-80b5-6566722f2658.png)

**Comment by Chef-Chungus** [comment]
Hi @facumartinarguello   - We aren't currently listing assets as default on the exchange which don't have/haven't had a Syrup pool, Farm, or IFO. 

Please fill out the form to apply for one of these
https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
