### ISSUE TITLE
Accidentally Sent ETH to Cake Public Contract Addresss

### ISSUE THREAD

**Issue by mastergaurang94** [pancakeswap/pancake-swap-interface#153]
Hi there,

I accidentally sent my ETH to the Cake public contract address. This is my first time buying an alt-coin and I made a mistake :(

Is there a way for me to ask the team to send back the money I sent? I wanted to purchase some CAKE coins, not send ETH to it's public contract address. I realize this may not be the place to ask but where is?

The transaction is here: https://etherscan.io/tx/0x726b67b75fd5f08aa4eb8379445fb15acada00f5ad151b7d6d2b9f6725f790ac

Gaurang

**Comment by xandercakes** [comment]
That's an ethereum tx. Cake isn't on ethereum network, looks like you sent it to a random address.
