### ISSUE TITLE
[Listing] Request listing for KOGE

### ISSUE THREAD

**Issue by BNB48ClubSirIan** [pancakeswap/pancake-swap-interface#157]
**Token information**
```
    {
      "name": "BNB48 Club Token",
      "symbol": "KOGE",
      "address": "0xe6df05ce8c8301223373cf5b969afcb1498c5528",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "/images/coins/KOGE.png"
    }
```
PR : https://github.com/pancakeswap/pancake-swap-interface/pull/156 , in this PR necessary info of KOGE was added in pancakeswap.json and token logo image file was also added.

**Comment by Chef-Chungus** [comment]
Hi @BNB48ClubSirIan   - We aren't currently listing assets as default on the exchange which don't have/haven't had a Syrup pool, Farm, or IFO. 

Please fill out the form to apply for one of these
https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
