### ISSUE TITLE
[Listing] Request listing for BORG and ROMS

### ISSUE THREAD

**Issue by locutusofborg111** [pancakeswap/pancake-swap-interface#160]
**Token information**
https://assimilate.finance
https://t.me/BORG_ResistanceIsFutile
https://twitter.com/BorgToken

BORG:
https://bscscan.com/token/0xe9828045632b32e2aac7f3a4c1511c0d8965576c

ROMS:
https://bscscan.com/token/0x1103ded5171c2f4e920fb95c2b28b8c94006ea6f

**Comment by Chef-Chungus** [comment]
Hi @locutusofborg111 - We aren't currently listing assets as default on the exchange which don't have/haven't had a Syrup pool, Farm, or IFO. 

Please fill out the form to apply for one of these
https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
