### ISSUE TITLE
[Listing] Request listing for Pie Token

### ISSUE THREAD

**Issue by pienetwork9** [pancakeswap/pancake-swap-interface#162]
**Token information**
```
{
      "name": "Pie Token",
      "symbol": "Pie",
      "address": "0x8b09b6eb1d263644a267dfb2b2bc8d6b0fb72e7d",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "/images/coins/pietoken.png"
    }
```

**Comment by Chef-Chungus** [comment]
Hi @pienetwork9  - We aren't currently listing assets as default on the exchange which don't have/haven't had a Syrup pool, Farm, or IFO. 

Please fill out the form to apply for one of these
https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
