### ISSUE TITLE
Not able to retrieve BNB Cake LP tokens after BRY IFO

### ISSUE THREAD

**Issue by jffz** [pancakeswap/pancake-swap-interface#183]
**Bug Description**
Not able to retrieve BNB Cake LP tokens after BRY IFO

**Steps to Reproduce**
Deposit Cake/BNB LP
Get no BRY
Try to claim LP

**Expected Behavior**
Retrieve deposited LP 

**Additional Context**
![screenshot](https://cdn.discordapp.com/attachments/554231046992822277/811259319559258172/image_2021-02-16_15-52-36.png)

**Comment by jffz** [comment]
Is it possible to have some kind of help please ? I have my bucks locked and can't do anything ...

**Comment by RabbitDoge** [comment]
This is not the right place to ask help about the product. 
This topic has been heavily discussed in the TG group. There was a bug yesterday, and now it's solved. If you still need help, ask in the official Telegram group.

**Comment by jffz** [comment]
Thanks for the info,I am one of those having participated to this heavy discusse issue on the TG group. 
I am here because the issue is still there for some of us like me  and just nobody answer on the TG group or twitter. I am still not able to retrieve my LP tokens.
Do your job please
