### ISSUE TITLE
[Listing] Request listing for {Ganjacoin}

### ISSUE THREAD

**Issue by legends420** [pancakeswap/pancake-swap-interface#184]
**Token information**
{
"name": "Ganjacoin",
"symbol": "MRJA",
"address": "0x75c002e249651e9a49b214f9c82898a2f6474dc1",
"chainId": 56,
"decimals": 18,
"logoURI": "/images/coins/MRJA.png"
},

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
