### ISSUE TITLE
[Listing] Request listing for {ACS + ACSI}

### ISSUE THREAD

**Issue by rossi256** [pancakeswap/pancake-swap-interface#199]
can't reopen #91 - please review our listing request - project has grown well -- https://github.com/pancakeswap/pancake-swap-interface/issues/91#issuecomment-781956624

{
"name": "ACryptoS",
"symbol": "ACS",
"address": "0x4197C6EF3879a08cD51e5560da5064B773aa1d29",
"chainId": 56,
"decimals": 18
},
{
"name": "ACryptoS(I)",
"symbol": "ACSI",
"address": "0x5b17b4d5e4009B5C43e3e3d63A5229F794cBA389",
"chainId": 56,
"decimals": 18
}

icon: https://app.acryptos.com/images/tokens/acs.svg

https://pancakeswap.info/pair/0x2366ec9ddd1eb27506fa2ed48da8f2d9e99ed3c7
https://pancakeswap.info/pair/0x699c58d77027ae44608808b3863c394a194d76f6

Website: https:/acryptos.com/

thanks!

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
