### ISSUE TITLE
[Listing] Request listing for Newscrypto

### ISSUE THREAD

**Issue by newscrypto** [pancakeswap/pancake-swap-interface#200]
**Token information**
{
      "name": "Newscrypto",
      "symbol": "NWC",
      "address": "0x968f6f898a6df937fc1859b323ac2f14643e3fed",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "/images/coins/NWC.png"
}
website: https://newscrypto.io

Newscrypto implemented a cross-chain solution for our holders to swap from our native chain (Stellar) to ERC20 and BEP20 variants. We would like to create a pool on pancake swap, but first, we would need our logo to be shown (so the pool looks credible and to prevent possible scam pools).

Currently, we are listed on:
https://coinmarketcap.com/currencies/newscrypto/markets/

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
