### ISSUE TITLE
[Listing] Request listing for {RECEH}

### ISSUE THREAD

**Issue by agussaifuddin** [pancakeswap/pancake-swap-interface#202]
**Token information**
{
"name": "Receh Token",
"symbol": "RECEH",
"contract": "0x87592031236e0838fda0ee53ee0cee9552ada964",
"chainId": 56,
"decimals": 18,
"logoURI": "https://recehpay.com/wp-content/uploads/2020/11/Receh-Token-Logo.png"
}
website: https://recehpay.com

ABOUT RECEH Token

RECEH Token is a modern day digital currency which primarily deals with online payment.
RECEH Token is one of advanced technology based crypto currency, Launched on 21nd february 2021.
RECEH Token used by RECEH Community for online payment purposes like purchase of a product online, crypto trade, business for giveaway, donation & other.

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
