### ISSUE TITLE
[Listing] Request listing for Crepe Token

### ISSUE THREAD

**Issue by lekhoi456** [pancakeswap/pancake-swap-interface#204]
**Token information**
Crepe Token
A token of Crepe.Finance - The next evolution DeFi exchange on Binance Smart Chain (BSC). 

Contract Address: https://bscscan.com//address/0xC3Dc6A4aEd6B6f43535aCFAA50Cd348eFcF0bC80
https://i.imgur.com/hqRaE2g.png

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
