### ISSUE TITLE
[Listing] Request listing for Wrapped Conceal (wCCX)

### ISSUE THREAD

**Issue by krypt0x** [pancakeswap/pancake-swap-interface#205]
**Token information**
{
      "name": "Wrapped Conceal",
      "symbol": "wCCX",
      "address": "0x21686F8ce003a95c99aCd297E302FAACf742F7d4",
      "chainId": 56,
      "decimals": 6
    }
    
    BscScan: https://bscscan.com/token/0x988c11625472340b7b36ff1534893780e0d8d841
    
    Logo: https://bscscan.com/token/images/concealnetwork_32.png

**Comment by krypt0x** [comment]
Let us know if you need anything else from our side. Thank you.

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website

**Comment by krypt0x** [comment]
@Chef-Chungus Hi, alright. Please check your Syrup Pool's form. Thanks
