### ISSUE TITLE
Add Roobee in the token list

### ISSUE THREAD

**Issue by DenisKaizer** [pancakeswap/pancake-swap-interface#21]
{
      "name": "ROOBEE",
      "symbol": "ROOBEE",
      "address": "0xa31b1767e09f842ecfd4bc471fe44f830e3891aa",
      "chainId": 56,
      "decimals": 18
}
LOGO:
![ROOBEE](https://user-images.githubusercontent.com/22869112/95184222-ba4a7a80-07cf-11eb-8f41-6b57f6ac8838.png)

**Comment by RabbitDoge** [comment]
Done
