### ISSUE TITLE
[Listing] Request listing for MilkyWay Token {MILK2}

### ISSUE THREAD

**Issue by PillarDevelopment** [pancakeswap/pancake-swap-interface#211]
Token information

 "symbol": "MILK2",

"name": "MilkyWay Token by SpaceSwap v2",

Contract Address: https://bscscan.com/token/0x4a5a34212404f30c5ab7eb61b078fa4a55adc5a5

img: https://i.imgur.com/jwmAVoC.png

Description: The SpaceSwap project aims to become the first and only one-stop-station for major DeFi protocols. It will provide users with a fair and profitable earnings sharing system, topped by MilkyWay (MILK2) coin rewards and MilkShake (SHAKE), to boost your earnings.

email: info@spaceswap.app
telegram: @pillarBlockchain
site: https://spaceswap.app/

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
