### ISSUE TITLE
[Listing] Request listing for GorillaYield.finance

### ISSUE THREAD

**Issue by dexit-crypto** [pancakeswap/pancake-swap-interface#213]
### Token information

```json
{
      "name": "GorillaYield.finance",
      "symbol": "yAPE",
      "address": "0x64b783a80d0c05bed0e2f1a638465a7ba3f4a6fb",
      "chainId": 56,
      "decimals": 8,
      "logoURI": "/images/coins/yAPE.png"
}
```

Description: `$yAPE` is a reflect token on the Binance Smart Chain. A `reflect` fee is applied to all $yAPE transactions
and redistributes tokens directly to wallets of holders. There is no need for `staking` or `farming`
websites since the reflect feature happens directly `on-chain`.

### Links
email: partner@gorillayield.finance
telegram: https://t.me/gorillayield_finance
site: https://gorillayield.finance/
coinmarketcap: https://coinmarketcap.com/currencies/gorillayield/
bsc explorer: https://bscscan.com/token/0x64b783a80d0c05bed0e2f1a638465a7ba3f4a6fb

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website
