### ISSUE TITLE
[Listing] Request listing for SALT

### ISSUE THREAD

**Issue by saltKosher** [pancakeswap/pancake-swap-interface#214]
**Token information**

https://saltswap.finance

https://saltswap.gitbook.io/salt/

https://twitter.com/SaltSwap

- SALT: 0x2849b1aE7E04A3D9Bc288673A92477CF63F28aF4
- MasterChef: 0xB4405445fFAcF2B86BC2bD7D1C874AC739265658
- Timelock: 0xB5cD51B879424a920513a66407BB041a9E904731 (delay: 24h)

**Comment by renatakixd** [comment]
SALT on pancake swap would be awesome

**Comment by wetlight** [comment]
New project with a very good team and community!

**Comment by kkilates** [comment]
Good team and very nice community!

**Comment by Chef-Chungus** [comment]
Hi We have just updated our listing requirements. Please resubmit and follow the guidelines. Due to high demand, listing now requires a Pool or IFO on the PancakeSwap website

**Comment by jetwebdev** [comment]
Yes, Please add Salt Coin 0x2849b1aE7E04A3D9Bc288673A92477CF63F28aF4 for Listing on PancakeSwap Website.
We have a pool. Can you share the link for us to see the new listing requirements?
