### ISSUE TITLE
[Listing] Request listing for Wrapped CCX (Conceal.Network)

### ISSUE THREAD

**Issue by krypt0x** [pancakeswap/pancake-swap-interface#224]
### Declaration

[X] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[X] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Wrapped Conceal

Token symbol: wCCX

Token address: 0x988c11625472340b7B36FF1534893780E0d8d841

Token decimals: 6

Project website: https://conceal.network/
```

### Logo

Please upload your logo in .png format with a size of 96\*96px
![conceal_network_ccx_96x96](https://user-images.githubusercontent.com/35565671/109237576-ba243900-77c9-11eb-91f3-0a6b220b1469.png)

**Comment by Nito91** [comment]
Great project and hard working team!

**Comment by boot2thrill** [comment]
Let's get this done!

**Comment by m42orionus** [comment]
great project !

**Comment by tvoodoo** [comment]
I personally like this project. Worth it.

**Comment by whatevertrademark** [comment]
I support these dudes 100% . Fam, let's bake some pancakes.

**Comment by ThrownLemon** [comment]
Please accept this PR! 👍

**Comment by Mugur46** [comment]
I like this project.nice team!

**Comment by whiteeagle01** [comment]
[https://conceal.network]()

**Comment by whiteeagle01** [comment]
💚

**Comment by okanist** [comment]
Great project and this project totally deserves it!

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.

**Comment by krypt0x** [comment]
> Due to high demand we have instated the following rule to keep our GitHub tidy:
> 
> ### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM
> Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
> 
> Any Listing issues/PRs will be closed.

Chungus, we've applied before opening this issue. Please have a look at it. Thank you.
