### ISSUE TITLE
[Listing] Request listing for {Agus Finance}

### ISSUE THREAD

**Issue by agussaifuddin** [pancakeswap/pancake-swap-interface#228]
### Declaration

[ ] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[ ] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Agus Finance

Token symbol: AFI

Token address: 0x246988285b48efd26488426fbc785074e7cdf148

Token decimals: 18

Project website: https://agus.finance
```

### 
![AFI](https://user-images.githubusercontent.com/40567253/109305862-32532480-77f3-11eb-8027-a9ce7ca3c001.png)

Please upload your logo in .png format with a size of 96\*96px

**Comment by Chef-Chungus** [comment]
@agussaifuddin  you did not confirm the declaration, we will be closing this issue

**Comment by agussaifuddin** [comment]
how to confirm?
