### ISSUE TITLE
Add Liquidity pool for BNB and BUSD

### ISSUE THREAD

**Issue by yehia67** [pancakeswap/pancake-swap-interface#241]
Hey,
I am trying to create a pool using BNB and BUSD on Binance testnet.  First I used the faucet token to get BNB and BUSD. The BNB was visible but for the BUSD, I had to use this address `0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee` I got it from biance testnet exploere. When I tried to create a liquidity pool with 1 BNB and 1 USBD. I got this error 
`(node:2168) UnhandledPromiseRejectionWarning: Error: gas required exceeds allowance or always failing transaction` 
I found you talked about the solution on issue [469](https://github.com/ethers-io/ethers.js/issues/469). I implement the exact solution
1- removed INIT_CODE_HASH from pancakeFactroy contract and redeploy it.
2- Redeploy PancakeRouter using the new panackeFatcory.
3- add the new PancakeRouter address in `src/constants/index.ts`
And I still got the same error? Could you please tell me what I may be doing wrong?
Thanks in advance.

**Comment by yehia67** [comment]
I changed the INIT_CODE hash, and it works. The pools transactions created https://testnet.bscscan.com/tx/0x463e69b359dd5b20d71dc5efadc28fc4cfc1ad0723523488e9f5084d3aee1f2a successfully

But I can't see the created pool on the frontend or use it for swapping.
https://drive.google.com/file/d/1gGNvDTRCA1jqu2e5eXRTYpd_st2Xj-cd/view?usp=sharing

**Comment by yongloon** [comment]
> I changed the INIT_CODE hash, and it works. The pools transactions created https://testnet.bscscan.com/tx/0x463e69b359dd5b20d71dc5efadc28fc4cfc1ad0723523488e9f5084d3aee1f2a successfully
> 
> But I can't see the created pool on the frontend or use it for swapping.
> https://drive.google.com/file/d/1gGNvDTRCA1jqu2e5eXRTYpd_st2Xj-cd/view?usp=sharing

same problem, who to solve this?
