### ISSUE TITLE
[Listing] Request listing for {ADD TOKEN NAME HERE}

### ISSUE THREAD

**Issue by pdafight** [pancakeswap/pancake-swap-interface#257]
### Declaration

[V] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[V] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: BSC-Peg Thunder Token

Token symbol: TT

Token address: 0x990E7154bB999FAa9b2fa5Ed29E822703311eA85

Token decimals: 18

Project website: https://www.thundercore.com/
```

### Logo

Please upload your logo in .png format with a size of 96\*96px
![ThunderCore](https://user-images.githubusercontent.com/48502835/110283982-02d6c000-801c-11eb-8e5e-970e9fc5e765.png)

**Comment by Chef-Chungus** [comment]
closing due to #256
