### ISSUE TITLE
[Listing] Request listing for BTC

### ISSUE THREAD

**Issue by herbertvinewtech** [pancakeswap/pancake-swap-interface#259]
How can i add BTC Token to the existing tokens list and your google forums link doesn't have token option it only have Syrup pool and IFO...so it is possible to add BTC Token...if not means what i have to do for achieving that?

**Comment by Chef-Chungus** [comment]
BTC token? Is this a wrapped BTC? We already have WBTC listed

**Comment by herbertvinewtech** [comment]
No its a normal BTC

**Comment by Chef-Chungus** [comment]
Please share the contract address

**Comment by herbertvinewtech** [comment]
okay i'll share the address and i need one more thing...where i want to make a log of exchange/swap and how can i do it?shall i take response from wallet or use approvelCallback method?
