### ISSUE TITLE
[BUG] Slippage Tolerance Modal doesn't work with localization despite having localization implemented. 

### ISSUE THREAD

**Issue by Chef-Chungus** [pancakeswap/pancake-swap-interface#272]
**Bug Description**
When a language other than English is enabled, and you open the slippage tolerance modal, the modal will show in English despite the translations being completed and TranslateString/useI18n being implemented. 

**Expected Behavior**
Slippage tolerance modal should be localized. 

**Additional Context**
![image](https://user-images.githubusercontent.com/71833681/111092537-acb4d000-8579-11eb-9a8c-eb1d30d0680e.png)

**Comment by memoyil** [comment]
Found the issue, will provide fix soon
