### ISSUE TITLE
Wallet Connect: unable to login

### ISSUE THREAD

**Issue by thanhnguyennguyen** [pancakeswap/pancake-swap-interface#30]
**Bug Description**
Unable to login pancakeswap using wallet connect (in trust wallet)

**Steps to Reproduce**
1. Go to http://pancakeswap.finance
2. Click on `Unlock Wallet`
3. Click `Wallet Connect`
4. Open TrustWallet with Binance Smart Chain wallet
5. Scan QR code

...

**Expected Behavior**
Can login with Binance Smart Chain account in Trust Wallet

**Actual Behavior**
It said `No account available`
![image](https://user-images.githubusercontent.com/17243442/95669014-619b2900-0ba5-11eb-9832-e644ac0704d8.png)

**Additional Context**

**Comment by hewigovens** [comment]
can you try multi coin wallet? I can unlock with Trust but not able to receive any signing requests. Does WalletConnect work or still in progress @pancake-swap @RichardPK ?

**Comment by thanhnguyennguyen** [comment]
Hi @hewigovens , @pancake-swap ,
If I use multicoin wallet or Ethereum wallet, I can login but can't receive any signing request

**Comment by RichardPK** [comment]
Yea interesting. I'd need to pass this onto @pancake-swap - I haven't worked on any of the wallet connection pieces.

@thanhnguyennguyen - I use Trust Wallet on iOS - accessing PancakeSwap via the in-app DApps browser automatically injects & presigns the connection for that session. If I have to unlock my wallet after that in-app I just select the 'Trust Wallet' option. 

On iOS - you'll need TestFlight and the beta version of Trust Wallet to get the DApp browser, instructions here - https://community.trustwallet.com/t/how-to-use-the-dapp-browser-on-ios/69390?ref=JLI1VBLA&utm_source=TrustTwitter&utm_medium=TrustSocial&utm_campaign=TrustSocial

**Comment by junzhuang-code** [comment]
I meet the same issue!!! It seems that pencakeswap could not fix this bug for a long time.

**Comment by Seetth** [comment]
> I meet the same issue!!! It seems that pencakeswap could not fix this bug for a long time.

Same here... So this is an old issue as I see

**Comment by RabbitDoge** [comment]
should be solved now

**Comment by tarikg1980** [comment]
I think i have the same issue now..Trying to connect trustwallet with pancake... 
Request of type 'wallet_requestPermissions' already pending for origin https://pancakeswap.finance. Please wait.

**Comment by memoyil** [comment]
Clean your browser cache and try again
