### ISSUE TITLE
Swap ended up $100 short out of $500

### ISSUE THREAD

**Issue by MosroHaden** [pancakeswap/pancake-swap-interface#301]
My 1st attempt at a swap, successful when checked on Bscscan, resulted in nothing even after 15 min! The 2nd try, also successful per BscScan, came up $100 short. What happened? All prices looked the same for both transactions.
![57F38735-FA1F-47C2-B602-68C4F7075B7B](https://user-images.githubusercontent.com/81275917/112250009-594c1d00-8c1e-11eb-91f3-c91ce41edf95.png)
![66D69137-91B9-47E4-A55C-E0E934E15B41](https://user-images.githubusercontent.com/81275917/112250046-6701a280-8c1e-11eb-931a-19b67cc5adcd.png)
![D402CB98-0DB8-41BD-BB74-23EE40FC00E2](https://user-images.githubusercontent.com/81275917/112250048-679a3900-8c1e-11eb-84cd-bbf150011811.png)
![1E67FCCA-A64E-473B-8652-4EE3EBE7C2AC](https://user-images.githubusercontent.com/81275917/112250051-68cb6600-8c1e-11eb-88ad-1bfea215d68d.png)

**Comment by ChefKai** [comment]
Hello, following the values from BscScan, you did not ended up $100 short but $49, and as SAFEMOON have a 10% burn fee on each transaction, it all adds up:

Your input size: $484
Burn fee from SAFEMOON:  $48.4 (10% of $484)
Your output size: $435.6 ($484 - $48.4)
+ adding the slippage; there was no issue on the swap or the executed price.

Please do your own research, or ask SAFEMOON team directly.
