### ISSUE TITLE
Display APY in staking page

### ISSUE THREAD

**Issue by thanhnguyennguyen** [pancakeswap/pancake-swap-interface#33]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Display APY in staking page 
https://pancakeswap.finance/staking
```
Total staked CAKE = Total Supply of SYRUP
NUMBER_BLOCK_IN_ONE_YEAR = 365 * 86400 /3
APY = 10 CAKE per block *NUMBER_BLOCK_IN_ONE_YEAR / Total Supply of SYRUP * 100%
```
**Describe alternatives you've considered**

**Additional context**
N/A

**Comment by RabbitDoge** [comment]
This page is not meant to be used anymore. Use https://pancakeswap.finance/syrup instead.
