### ISSUE TITLE
This condition will always return true since the function is always defined. Did you mean to call it instead? 

### ISSUE THREAD

**Issue by github2k20** [pancakeswap/pancake-swap-interface#353]
**Bug Description**
This condition will always return true since the function is always defined. Did you mean to call it instead? TS2774

100 | if (resolve && reject) {
| ^
101 | if ('error' in result) {
102 | reject(new RequestError(result?.error?.message, result?.error?.code, result?.error?.data))
103 | } else if ('result' in result) {

**Steps to Reproduce**

1. Clone the project
2. Delete the existing yarn.lock file
3. yarn
4. yarn start
   ...

**Expected Behavior**
The error should not appear

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by nizarrahmat** [comment]
same error in here

**Comment by github2k20** [comment]
Not completely sure why its happening but replacing the package.json and yarn.lock file of your project with original pancake repo ones will resolve the issue.

**Comment by github2k20** [comment]
Not completely sure why its happening but replacing the package.json and yarn.lock file of your project with original pancake repo ones will resolve the issue.

**Comment by nizarrahmat** [comment]
which package.json and yarn.lock files ?

**Comment by hosekhoshtaghaza** [comment]
Removing the second condition from...

`
100 | if (resolve && reject) {
`

...in src/connectors/NetworkConnector.ts allowed it to build for me. Resolve and reject are functions and both return true by default. Just having resolve still ensures byKey has been destructured and clears the always true error, despite also always being true.
