### ISSUE TITLE
CROWDIN_APIKEY and REACT_APP_CROWDIN_PROJECTID 

### ISSUE THREAD

**Issue by dj202095** [pancakeswap/pancake-swap-interface#36]
In order for the Crowdin API queries to work - you will need REACT_APP_CROWDIN_APIKEY & REACT_APP_CROWDIN_PROJECTID env variables set in your root .env.development.local file - please contact a dev if you need these.

Can you please help me with CROWDIN_APIKEY and REACT_APP_CROWDIN_PROJECTID  so that I can run a local copy of pancake. It used to work till last update.

**Comment by RabbitDoge** [comment]
We don't provide these keys for people outside of the team unfortunately. If the problem persist, you can submit a pr to allow the application to run smoothly without the keys.
