### ISSUE TITLE
StableXSwap Logo & Contract Address

### ISSUE THREAD

**Issue by defidevguy** [pancakeswap/pancake-swap-interface#37]
http://stablexswap.com/

{
"name": "StableXSwap/b",
"symbol": "STAX/b",
"address": "0x0da6ed8b13214ff28e9ca979dd37439e8a88f6c4",
"chainId": 56,
"decimals": 18,
"logoURI": "/images/coins/STAX.png"
},
STAX
![image](https://user-images.githubusercontent.com/70198668/96256291-f7daaf00-0fea-11eb-8e9b-bbb5e422371a.png)

https://pbs.twimg.com/profile_images/1315920956276133888/AFVRwlv4_400x400.jpg

**Comment by RabbitDoge** [comment]
Done
