### ISSUE TITLE
ADD ROYAL : Royal Finance

### ISSUE THREAD

**Issue by riyanhid1** [pancakeswap/pancake-swap-interface#40]
Name : Royal Finance
Address : 0x2e4b9a52836aeb2e6809fa760c9b799885fd6c34
Symbol : ROYAL
Decimals : 18
ChainID : 56
Logo : 
![0x2e4b9a52836aeb2e6809fa760c9b799885fd6c34](https://user-images.githubusercontent.com/55166625/96371199-bda81380-118a-11eb-8271-e9eeef0a978b.png)

**Comment by Chef-Chungus** [comment]
Thank you for your request - Unfortunately, we aren't listing non-pool/farm/ifo assets at this time.
