### ISSUE TITLE
Add MARS, YFMR to the list of token

### ISSUE THREAD

**Issue by yfmars-dev** [pancakeswap/pancake-swap-interface#47]
Please, add MARS, YFMR token to the tokens list. Our website http://yfmars.app/

 >{
      "name": "marsUSD",
      "symbol": "MARS",
      "address": "0x7e440598f8f63fccd9b12a606263a02a06cfb16a",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "/images/coins/MARS.png"
    },
    {
      "name": "YFMARS",
      "symbol": "YFMR",
      "address": "0x9b3ed616c4ff49023a89f4da8b85cce22c0f8cb3",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "/images/coins/YFMR.png"
    }

> 

https://github.com/yfmars-dev/pancake-swap-interface/blob/master/public/images/coins/MARS.png
https://github.com/yfmars-dev/pancake-swap-interface/blob/master/public/images/coins/YFMR.png

**Comment by Chef-Chungus** [comment]
Thank you for your request - Unfortunately, we aren't listing non-pool/farm/ifo assets at this time.
