### ISSUE TITLE
Add Zombie Token

### ISSUE THREAD

**Issue by DoomMetalGuy** [pancakeswap/pancake-swap-interface#49]
Name : Zombie
Address : 0xFCaeED4C19228f15971933B6C7aB24C671991Fd6
Symbol : ZOMBIE
Decimals : 18
ChainID : 56
Logo : https://www.trickortreat.vip/favicon.png

**Comment by Chef-Chungus** [comment]
Thank you for your request - Unfortunately, we aren't listing non-pool/farm/ifo assets at this time.
