### ISSUE TITLE
CHEAT NIJA LOGO

### ISSUE THREAD

**Issue by CryptoFishF** [pancakeswap/pancake-swap-interface#57]
{
  "name": "CHEAT NIJA",
  "symbol": "CHEAT",
  "address": "0x73ea129d538bb1e75c1c5e99a77666409005681e",
  "chainId": 56,
  "decimals": 18,
   "logoURI": "cheatninja.png"
},
![cheatninja](https://user-images.githubusercontent.com/57900650/98914156-45bbd780-2503-11eb-8311-834b572cd246.png)

**Comment by Chef-Chungus** [comment]
Thank you for your request - Unfortunately, we aren't listing non-pool/farm/ifo assets at this time.
