### ISSUE TITLE
Whitelist BUNNY Token Request

### ISSUE THREAD

**Issue by pancakebunny-dev** [pancakeswap/pancake-swap-interface#78]
Request a token whitelist. ref: #64 
Please let me know if there are any other requirements I have to do for whitelisting.

{
      "name": "Bunny Token",
      "symbol": "BUNNY",
      "address": "0xC9849E6fdB743d08fAeE3E34dd2D1bc69EA11a51",
      "chainId": 56,
      "decimals": 18
}

[BUNNY.png](https://raw.githubusercontent.com/PancakeBunny-finance/pancake-swap-interface/bc6be869ca5a4f6700c8d33778e0342cdd00157a/public/images/coins/BUNNY.png)

---
BUNNY PROJECT
PancakeBunny is a new and rapidly growing DeFi yield aggregator that is used for PancakeSwap. The PancakeBunny protocol empowers farmers to leverage their yield-seeking tendencies to optimize yield compounding strategies. We are providing strategies for the various needs of farmers from the highest yield seekers to the risk reward optimizing smart investors

website: https://pancakebunny.finance
telegram: https://t.me/pancakebunnyfinance
email: hello@pancakebunny.finance
twitter: https://twitter.com/PancakeBunnyFin
pancakeswap: https://pancakeswap.info/token/0xc9849e6fdb743d08faee3e34dd2d1bc69ea11a51
coingecko: https://www.coingecko.com/en/coins/pancake-bunny
bscscan: https://bscscan.com/token/0xc9849e6fdb743d08faee3e34dd2d1bc69ea11a51

**Comment by Chef-Chungus** [comment]
Thank you for your request - Unfortunately, we aren't listing non-pool/farm/ifo assets at this time.
