### ISSUE TITLE
Local dev-experience - error on localhost when trying to set up exchange

### ISSUE THREAD

**Issue by RichardPK** [pancakeswap/pancake-swap-interface#8]
**Bug Description**
- While on either MAIN NET(56) or TEST NET (97), attempting to create an exchange pair throws a `"Failed to fetch multicall chunk"` error after selecting the 'to' token.
- It then throws this error consistently, on a timeout
- Error: 

```
Failed to fetch multicall chunk [{…}] 56 Error: call revert exception (method="aggregate((address,bytes)[])", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.5)
```

**Steps to Reproduce**
1. Go to "http://localhost:3000/#/swap"
2. Click on "Select a token"
3. Select 'BUSD'
5. Add '1' to either value, and it will remove the other value. The swap rate has not been discovered.
...

**Expected Behavior**
- No error when selecting second token in pair, success message like:
```
Success to fetch multicall chunk (21) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 56
```
- When value of one token is input, you get an exchange rate.

**Additional Context**
Screen capture of behaviour: https://www.loom.com/share/962e7d96bd3b416a87f1db1f73e26932

**Comment by pancake-swap** [comment]
Could you check the V1 factory address, it might result in an error response. However,  the newest code works well on my side.
