### ISSUE TITLE
[Listing] Request listing for ACS, ACSI

### ISSUE THREAD

**Issue by acryptosx** [pancakeswap/pancake-swap-interface#91]
{
"name": "ACryptoS",
"symbol": "ACS",
"address": "0x4197C6EF3879a08cD51e5560da5064B773aa1d29",
"chainId": 56,
"decimals": 18
},
{
"name": "ACryptoS(I)",
"symbol": "ACSI",
"address": "0x5b17b4d5e4009B5C43e3e3d63A5229F794cBA389",
"chainId": 56,
"decimals": 18
}

icon: https://app.acryptos.com/android-chrome-512x512.png

We are getting ~$50K volume/day:
https://pancakeswap.info/pair/0x2366ec9ddd1eb27506fa2ed48da8f2d9e99ed3c7
https://pancakeswap.info/pair/0x699c58d77027ae44608808b3863c394a194d76f6

Website: https:/acryptos.com/

We are currently listed on:
TrustWallet
https://www.coinbase.com/price/acryptos
https://coinmarketcap.com/currencies/acryptos/
https://www.coingecko.com/en/coins/acryptos
https://dappradar.com/binance-smart-chain/defi/acryptos

**Comment by Chef-Chungus** [comment]
Thank you for your request - Unfortunately, we aren't listing non-pool/farm/ifo assets at this time.

**Comment by rossi256** [comment]
Dear @Chef-Chungus,
Mik from Core DAO AcryptoS here.
could you please review this request for whitelist and other collaborations - 
ACryptoS is growing rapidly, we are fully supporting PCS and would appreciate official cooperation. a Whitelist of our native tokens $ACS and $ACSI would be a great first step.

Total TVL now 500M$ - we are more and more recognised also by BSC Community management.

we are happy to join Syrup Pool and other possible collaborative actions!

Technical details above - more collaborative options are welcome - would appreciate a TG workgroup, please message any time in our public DAO channel https://t.me/acryptosdao to get in touch.

Congrats for your/our persistence and well deserved success coming in these days!
